//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinev1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cineEntities : DbContext
    {
        public cineEntities()
            : base("name=cineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<funcion> funcion { get; set; }
        public virtual DbSet<pelicula> pelicula { get; set; }
        public virtual DbSet<proyeccion> proyeccion { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<sala> sala { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
