//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinev2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public decimal em_idEmpleado { get; set; }
        public string em_nombre { get; set; }
        public string em_apellido1 { get; set; }
        public string em_apellido2 { get; set; }
        public Nullable<decimal> em_telefono { get; set; }
        public string em_direccion { get; set; }
        public Nullable<decimal> em_salario { get; set; }
        public Nullable<decimal> suc_idSucursal { get; set; }
    
        public virtual sucursal sucursal { get; set; }
    }
}
